name: CI

on:
  pull_request:

concurrency:
  group: eslint-config-CI-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          node-version-file: .nvmrc
          check-latest: true
          cache: npm

      - run: npm ci

      - name: Test
        run: npm test
