name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: eslint-config-CD-${{ github.head_ref }}
  cancel-in-progress: true

env:
  GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name || github.actor }}
  GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email || '<>' }}
  GIT_COMMITTER_NAME: ${{ github.event.head_commit.committer.name || github.actor }}
  GIT_COMMITTER_EMAIL: ${{ github.event.head_commit.committer.email || '<>' }}
  GIT_CREDENTIALS: ${{ format('{0}:{1}', github.event.head_commit.committer.name,secrets.GITHUB_TOKEN) }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          node-version-file: .nvmrc
          check-latest: true
          cache: npm

      - run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
