name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "package.json"
      - "package-lock.json"
      - ".github/**"
      - "README.md"

concurrency:
  group: eslint-config-CD-${{ github.head_ref }}
  cancel-in-progress: true

env:
  GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name || github.actor }}
  GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email || '<>' }}
  GIT_COMMITTER_NAME: ${{ github.event.head_commit.committer.name || github.actor }}
  GIT_COMMITTER_EMAIL: ${{ github.event.head_commit.committer.email || '<>' }}
  GIT_CREDENTIALS: ${{ format('{0}:{1}', github.event.head_commit.committer.name,secrets.GITHUB_TOKEN) }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          registry-url: "https://registry.npmjs.org"
          node-version-file: .nvmrc
          check-latest: true
          cache: npm

      - run: npm ci

      - name: Release
        run: |
          npm version minor
          npm publish --access public
          git push
