name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "package.json"
      - "package-lock.json"
      - ".github/**"
      - "README.md"

concurrency:
  group: eslint-config-CD-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version-file: .nvmrc
          check-latest: true
          cache: npm

      - run: npm ci

      - name: Release
        run: |
          npm version minor
          npm publish --access public
          git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
